- lib/base/error-handler.js
- lib/base/server.js
- npm-shrinkwrap.json
- package.json
Support node v14.15.1
As upgrade node version to v14.15.1, deprecated API occurs.
Accordingly fix the API and update lib/base/server.js.
1. Before CLI test, change settings
- Upgrade node version to v14.15.1
- Remove node_modules
- Re-install npm as 'npm install'
2. Check below commands
- ares-server and click or open returned url
- ares-inspec and --open option
- ares-launch -H option
3. Pass unit test on ose and auto
4. Pass eslint
[PLAT-128958] Support node v14.15.1
> Support node v14.15.1

- lib/generator.js
Support ares-generate on node v14.15.1
As upgrade node version to v14.15.1, sometimes timing issue occurs
on ares-generate. Accordingly update and fix lib/generator.js.
1. Before CLI test, change settings
- Upgrade node version to v14.15.1
- Remove node_modules
- Re-install npm as 'npm install'
2. Check below commands and test each command at least 3 times
2-1. generate hosted_webapp
- ares-generate.js -t hosted_webapp webapp -p "url=www.google.com"
- cat webapp/index.html
- check "www.google.com" exist in source code
2-2. generate qmlapp
- ares-generate.js -t qmlapp qmlapp -p "id=com.test.app"
- cat qmlapp/main.qml
- check appId: "com.test.app" exist in source code
3. Pass unit test on ose and auto
4. Pass eslint …
> Support ares-generate on node v14.15.1

- lib/base/error-handler.js
- lib/base/server.js
Remove error text in run server function
When requestHandler is null when web server runs,
the operation is finished due to error showing.
- Remove requestHandler error print
- Unit test passed on OSE/Auto target
- ESLint done
- Run CLI command on Auto target
$ ares-generate -t webapp sampleWebApp
$ ares-launch --hosted sampleWebApp --display 1
[PLAT-129808] [SDK_CLI] Unable to launch "sampleWebApp" on display 1
> Fix ares-launch --hosted bug

- lib/base/novacom.js
- lib/install.js
- lib/package.js
Update deprecated Buffer on node v14.15.1
Buffer() is deprecated on node v14.15.1,
so the API fixed to instead another APIs
1. Before CLI test, change settings
- Upgrade node version to v14.15.1
- Remove node_modules
- Re-install npm as 'npm install'
2. Check below commands to make sure it works without warning messages
- node ares-package.js webapp
- node ares-install.js com.domain.app_1.0.0_all.ipk
- node ares-package.js -s ../spec/tempFiles/sign/signPriv.key
-crt ../spec/tempFiles/sign/sign.crt webapp
3. Pass unit test on auto target and ose emulator
4. Pass eslint
[PLAT-129806] Update deprecated Buffer on node v14.15.1
> Update deprecated Buffer on node v14.15.1

- README.md
- files/help/ares.help
Update ares help and README files
- Update ares help file
- Fix typos and update compatibility in README file
2. Check ares -h
3. Check README file
[PLAT-131090] Release CLI v2.0.3 for OSE 2.9.0
> Update ares help and README files

- .eslintrc.js
- spec/jsSpecs/ares-config.spec.js
- spec/jsSpecs/ares-device.spec.js
- spec/jsSpecs/ares-generate.spec.js
- spec/jsSpecs/ares-inspect.spec.js
- spec/jsSpecs/ares-install.spec.js
- spec/jsSpecs/ares-launch.spec.js
- spec/jsSpecs/ares-package.spec.js
- spec/jsSpecs/ares-pull.spec.js
- spec/jsSpecs/ares-push.spec.js
- spec/jsSpecs/ares-server.spec.js
- spec/jsSpecs/ares-setup-device.spec.js
- spec/jsSpecs/ares-shell.spec.js
- spec/jsSpecs/ares.spec.js
- spec/jsSpecs/common-spec.js
Detect node warning in unit test
Add detecting code to detect node warnings through unit test
1-1. Before CLI test, change settings
- node v14.15.1
- revert git to Update version 2.0.1(sha:519dd1836)
- cherry-pick this commit on reverted git
1-2. Run unit test on below condition
- failed test of ares-package/install/launch/inspect/server
2. Pass unit test on ose and auto
3. Pass eslint
[PLAT-131258] Implement node deprecated detect condition in TC
> Detect node warning in unit test

- lib/shell.js
- spec/jsSpecs/ares-shell.spec.js
Fixed differences in ares-shell results
Fixed differences in ares-shell environment variable results
Whether in ssh's interactive mode, environment variable is different
Modified to ouput the same environment variable as through ares-shell
2. Pass eslint
3. Check if the results of the two commands below are the same
- ares-shell and then enter echo $PATH in connected shell
- ares-shell -r 'echo $PATH'
4. Check below command and result
- ares-shell -r "luna-send -n 1 -f luna://com.domain.app.service/hello '{}'"
{
"returnValue": true,
"Response": "Hello, World!"
}
[PLAT-134675] ares-shell's output is different from the actual results
> Fixed differences in ares-shell results

- lib/shell.js
- spec/jsSpecs/ares-shell.spec.js
Fixed differences in ares-shell results on session
Modified to ouput the same environment variable as through ares-shell on session
2. Pass eslint
3. Check results of below commands on auto device as root user and emulator as developer
- ares-shell.js -r "echo \$PATH"
- ares-shell.js -r 'echo $PATH'
- ares-shell.js -r 'echo $PATH' -dp 1
- ares-shell.js -r "echo \$PATH" -dp 1
- ares-shell.js -r "pwd"
- ares-shell.js -r "pwd" -dp 1
- ares-shell -r "luna-send -n 1 -f luna://com.domain.app.service/hello '{}'"
- ares-shell -r "luna-send -n 1 -f luna://com.domain.app.service/hello '{}'" -dp 1
[PLAT-135931] Support to output the same environment variable
using ares-shell on auto session
> :Release Notes:

- lib/device.js
Fix ares-device --capture bug on windows
In windows, an error stating that the path is invalid occurred.
So, this bug is fixed.
1. Pass unit test on ose, auto and windows
2. Pass eslint
3. Verify with CLI commands
- ares-device.js -c
- ares-device.js -c -dp 1
- ares-device.js -c webOSCap -dp 1
- ares-device.js -c webOSCap/test1.bmp [or test1.jpg or test1.png]
[PLAT-138240] Fix bug of ares-device --capture on windows
> Fix ares-device --capture bug on windows

- spec/jsSpecs/ares-shell.spec.js
Update unit test of ares-shell
Since cmd processing is different between Windows and Linux,
the unit test is updated accordingly.
1. Pass unit test on ose/auto and linux/windows
2. Pass eslint
[PLAT-138905] Update unit test of ares-shell
> Update unit test of ares-shell

- bin/ares-setup-device.js
- lib/base/error-handler.js
- lib/base/setup-device.js
- spec/jsSpecs/ares-setup-device.spec.js
Constrain device name on setup-device
Allow number, letter, -, _, # for adding device name
Add negative TC on setup-device spec file
1. Unit test passed on OSE/Auto target
2. eslint passed.
- Add device name has "-, _, #" successfully
`$ ./ares-setup-device.js -a auto_-#1` 
- Invalid device name can not be added. Print error message.
`$ ./ares-setup-device.js -a invalid@`
-> Invalid device name. Please use letters, numbers and allowed characters ('-', '_', '#')
[PLAT-137681] Add constraint for device name on ares-setup-device
> Constraint device name

- bin/ares-install.js
- bin/ares-package.js
- lib/device.js
- lib/util/json.js
- spec/jsSpecs/ares-install.spec.js
Make ares-install -F result more readable
Make ares-install -F result more readable
Current result of ares-install -F is hard to read
Show app's detail infomation as ares-device -s option
1. Passed Unit test in OSE & Auto target
2. Passed eslint
a. Install apps using ares-install
b. $ ares-install -F
id : com.domain.app
transparent : false
... 
c. Check "$ares-install -l" shows correct list
d. Check "$ares-device -s" on Auto. Check the result format 
[PLAT-134674] Make ares-install -F result more readable
> Improve applist

- lib/base/error-handler.js
- lib/base/server.js
- lib/device.js
Apply error heading to ares-server
- When ares-server --port executed with already used port
the error message is printed with "uncaughtException"
- Apply error heading to ares-server error
- Remove unused error handing in ares-device -i option
1. Passed unit test ose & auto target
2. Passed eslint
- Open 1st terminal and execute ares-sever with --port option
$ ./ares-server.js --port 12345 sampleWebApp
- Open 2nd terminal and execute the same command
$ ./ares-server.js --port 12345 sampleWebApp
ares-server ERR! [syscall failure]: listen EADDRINUSE: address already in use :::12345
ares-server ERR! [Tips]: An attempt to bind a server to a local address failed. Please check the IP address or the port number
- …
> Apply error heading to ares-server

- lib/log.js
- spec/jsSpecs/ares-log.spec.js
Support output format in file option on ares-log
- Modify output option is applied to file option on ares-log
- Update unit test case
2. Pass eslint
3. Check below command and output format
- ares-log --file system.journal --output json
[PLAT-142907] Support output format in file option on ares-log
> Support output format in file option on ares-log

- bin/ares-config.js
- bin/ares-log.js
- bin/ares.js
Change ares-command -v to consistent behavior
ares, ares-config and ares-log -v option are behaved differently.
So, changed them to consistent behavior.
2. Pass eslint
3. Check below command and printed help message with verbose log
- ares -v
- ares-config -v
- ares-log -v
[PLAT-143017] Change ares-command -v to consistent behavior
> Change ares-command -v to consistent behavior

- lib/log.js
Support to save file in follow option on ares-log
Modify to support both save and follow options at same time
1. Pass unit test on ose and auto emulator
2. Pass eslint
3. Check below command
- ares-log -f -s saved.log
[PLAT-143147] Support to save file in follow option on ares-log
> Support to save file in follow option on ares-log

- bin/ares-launch.js
- lib/base/error-handler.js
- lib/device.js
- lib/inspect.js
- lib/session.js
Add empty session tips for Auto
After flashing booting, user should select "profile icon" on the screen.
At this time, the session list is empty. So, CLI commands print
unexpected results. Add tips message to user
1. Before run TC, you must select a profile on each display.
TC passed on AUTO & OSE target and Auto emulator.
2. eslint passed
a. boot Auto board. The login UI is shown
b. Run CLI commands. "select profile" tips should be printed.
```
$ ./ares-install.js com.domain.app_1.0.0_all.ipk 
$ ./ares-launch.js -r
$ ./ares-launch.js -H sampleWeb
$ ./ares-launch.js -c com.test.app
$ ./ares-device.js -s
$ ./ares-inspect.js -s com.domian.app.test
$ ./ares-install.js -l
$ ./ares-install.js -F
$ …
```
> Add empty session tips for Auto

- bin/ares-setup-device.js
- lib/base/error-handler.js
- lib/log.js
Fix invalid value error bug in ares-setup-device
- If user gives invalid value in ares-setup-device's query mode, 
CLI shows "length" error, which is not expected message
- In query error case, have to return "string" type of error message.
- Change changeErrMsg to getErrMsg in log library
1. TC passed on OSE/Auto target & Auto emulator.
2. eslint passed
- Give invalid device name
```
$ ares-setup-device
Enter Device Name: emulator // Exist device name
>> The specified value already exists
Enter Device Name: 123 // Invalid device name
>> Invalid device name. The device name should consist of letters, numbers, and special characters ('-','_','#') and should start with letters or '_'
Enter Device Name:     // …
```
> Change getErrMsg to getErrMsgMap()

- lib/launch.js
Fix connection error in ares-launch -H option
- ares-launch -H shows "lunaAddr" error message with emulator turned off
- Fix to it show "connection" error message instead of "lunaAddr"
1. TC passed on OSE target & emulator.
2. ESLint passed
3. Verified with CLI commands with emulator turned off
$ ./ares-launch.js -H sampleWeb -d emulator
ares-launch ERR! [syscall failure]: connect ECONNREFUSED 127.0.0.1:6622
ares-launch ERR! [Tips]: Connection refused. Please check the device IP address or the port number
[PLAT-138374] Prepare to system test of CLI v2.2.0
> Fix emulator connection of ares-launch -H option

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
Update version to 2.2.0
- Update version in package.json and npm-shrinkwrap.json
- Update CHANGELOG.md
1. Install CLI 2.2.0 package using below command
$sudo npm uninstall -g @webosose/ares-cli
$sudo npm install -g https://github.com:webosose/ares-cli.git#Update_version_2.2.0
2. Check version using below command
$ares -V
> Version: 2.2.0
[PLAT-141834] Prepare CLI v2.2.0 release for OSE 2.11.0
> Update version to 2.2.0

- lib/inspect.js
If `LG_WEBOS_CUSTOM_SDK_HOME` has set,  `ares-inspect.cmd --app com.company.package --open` will not open browser properly. This PR fixed this issue.
> Fixed browser invocation

- lib/base/error-handler.js
- lib/base/novacom.js
- lib/device.js
- lib/pull.js
- spec/jsSpecs/ares-device.spec.js
- spec/jsSpecs/common-spec.js
Handle directory permission error
- Mac(M1) shows "EROFS" error when ares-device negative case executed
with read-only files system path so that CLI Unit test failed.
- Change the TC to get the same error text on Windows, Linux and Mac
- Add "EROFS" CLI tips message
- Fix "ares-device -c /" error message 
1. Passed CLI Unit test
2. Passed ESlint
3. Give ares-device -c with the read-only file system path on Mac(M1)
```
$ ./ares-device.js -c /
$ ./ares-device.js -c /rootDir
[Info] Set target device : rpi4
ares-device ERR! [syscall failure]: EROFS: read-only file system, [open/make] 'FILEPATH'
ares-device ERR! [Tips]: Please check if the path is writable <FILEPATH>
```
4. Give ares-device -c with the "root(/)" path on Linux
```
$ …
```
> Handle directory permission error

- spec/jsSpecs/common-spec.js
Add time interval setting in unit test
- Sometimes unit test failure due to time out occurs.
when executing unit test depending on host pc performance.
- Added time interval setting when run the unit test to solve the problem.
1. Pass unit test on ose
2. Pass eslint
3. Check time interval setting and test result
3-1. Change default time interval to fail the unit test
3-2. Check to no unit test failure when executing unit test command as like,
$ jasmine --device=ose --ip=123.456.789.10 --timeInterval=12000
[WRN-2921] Add function to modify default timeout interval
> Add time interval setting in unit test

- bin/ares-device.js
- files/help/ares-device.help
- lib/base/error-handler.js
- lib/device.js
- npm-shrinkwrap.json
- package.json
- spec/jsSpecs/ares-device.spec.js
Support save options for resource-monitor
- Add --save(-s) option to save resource usage result to .csv file
- Add --id-filter(-id) option for app or service ID
- Hide --session-information from ares-device help
- Add csv-wirter npm module to package.json
- Update help file
- Add related TC
1. Pass unit test on ose
2. Pass eslint
3. Check the generated csv file with resource-monitor options
$ ares-device -r -s -t 1
$ ares-device -r -s result.csv -t 1
$ ares-device -r -l -t 1 -s
$ ares-device -r -id com.domain.app -t 1 -s
$ ares-device -r -s test.abc -t 1 // error case
$ ares-device -r -s invalid/test.csv // error case
[WRN-9484] Implement ares-device -r --save option
> Support csv file

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
Update version 2.4.0
- Update version in package.json and npm-shrinkwrap.json
- Update CHANGELOG.md
1. Install CLI 2.4.0 package using below command 
$ sudo npm uninstall -g @webosose/ares-cli 
$ sudo npm install -g https://github.com:webosose/ares-cli.git#Update_version_2.4.0
2. Check version using below command $ ares -V
> Version: 2.4.0
[WRP-8976] Prepare to release CLI v2.4.0
> Update version 2.4.0
